#!/bin/bash


# Arduino has the nasty habit of specifying the real path in preferences.txt,
# instead of the path using the `current` symlink. This sed magic replaces all
# real paths to $SNAP_USER_DATA with ones using the `current` symlink.
#   Fixes https://github.com/snapcrafters/arduino/issues/4
snap_user_base=$(dirname "$SNAP_USER_DATA")
for perf_file in "$SNAP_USER_DATA"/.arduino*/preferences.txt; do
  [ -f "$perf_file" ] || continue
  sed -i -r "s/${snap_user_base//\//\\/}\/[0-9]+\//${snap_user_base//\//\\/}\/current\//g" "$perf_file"
done



APPDIR="$(dirname -- "$(readlink -f -- "${0}")" )"

for LIB in \
    "$APPDIR"/java/lib/rt.jar \
    "$APPDIR"/java/lib/tools.jar \
    "$APPDIR"/lib/*.jar \
    ;
do
    CLASSPATH="${CLASSPATH}:${LIB}"
done
export CLASSPATH

LD_LIBRARY_PATH=$APPDIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

export PATH="${APPDIR}/java/bin:${PATH}"

export JAVA_TOOL_OPTIONS=`echo $JAVA_TOOL_OPTIONS | sed 's|-javaagent:/usr/share/java/jayatanaag.jar||g'`

JAVA=java
if [ -x "$APPDIR/java/bin/java" ]; then
  JAVA=$APPDIR/java/bin/java
fi

# Collect options to java in an array, to properly handle whitespace in options
JAVA_OPTIONS=("-DAPP_DIR=$APPDIR")

# Only show the splash screen when no options are present
if [[ "$@" != *"--"* ]] ; then
	JAVA_OPTIONS+=("-splash:$APPDIR/lib/splash.png")
fi

JAVA_OPTIONS+=("-Duser.home=${SNAP_USER_DATA}")

"$JAVA" "${JAVA_OPTIONS[@]}" processing.app.Base "$@"
