#!/bin/bash

GROUP=$(stat -c '%G' /dev/ttyS0)

YAD_TITLE="Grant permissions"
TEXT1="\
<b>WARNING\\n\\n\
This snap is broken and not maintained anymore.</b> Please switch to the <tt>arduino</tt> snap by opening a terminal and running the following commands.\\n\
"
COMMAND1="\
<tt>sudo snap remove arduino-mhall119</tt>\
"
COMMAND2="\
<tt>sudo snap install arduino</tt>\
"
TEXT2="\
\\n\
If you have any problems, please let us know by creating an issue here:\\n\
"
URL="\
https://github.com/snapcrafters/arduino/issues/\
"
TEXT4="\\n\\n"

if [[ ! -f $SNAP_USER_COMMON/dont-warn-unsupported ]]; then
    # I'm using `form` here instead of `text`, because that allows me to split
    # the text into multiple parts which can each be selected independently.
    yad \
    --title="$YAD_TITLE" \
    --form \
    --center \
    --width=600 \
    --field="$TEXT1":LBL \
    --field="$COMMAND1":LBL \
    --field="$COMMAND2":LBL \
    --field="$TEXT2":LBL \
    --field="$URL":LBL \
    --field="$TEXT4":LBL \
    --field="Don't show this warning again":CHK \
    --focus-field=2 \
    --on-top \
    --borders=50 \
    --selectable-labels \
    --button=gtk-ok 2>&1 | grep TRUE && touch $SNAP_USER_COMMON/dont-warn-unsupported
fi

exec "$@"
